name: Cypress Tests (Kali Linux)

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    container:
      image: kalilinux/kali-rolling

    steps:
      - name: Exibir arte ASCII personalizada
        run: |
          echo "   ####   ##  ##   ######   ######   #######   #####    #####              ##     ##   ##  ######    #####   ##   ##    ##     ######    ####     #####   ##   ##"
          echo "   ##  ##  ##  ##    ##  ##   ##  ##   ##   #  ##   ##  ##   ##            ####    ##   ##  # ## #   ##   ##  ### ###   ####    # ## #     ##     ##   ##  ###  ##"
          echo "  ##       ##  ##    ##  ##   ##  ##   ## #    #        #                 ##  ##   ##   ##    ##     ##   ##  #######  ##  ##     ##       ##     ##   ##  #### ##"
          echo "  ##        ####     #####    #####    ####     #####    #####            ##  ##   ##   ##    ##     ##   ##  #######  ##  ##     ##       ##     ##   ##  ## ####"
          echo "  ##         ##      ##       ## ##    ## #         ##       ##           ######   ##   ##    ##     ##   ##  ## # ##  ######     ##       ##     ##   ##  ##  ###"
          echo "   ##  ##    ##      ##       ##  ##   ##   #  ##   ##  ##   ##           ##  ##   ##   ##    ##     ##   ##  ##   ##  ##  ##     ##       ##     ##   ##  ##   ##"
          echo "    ####    ####    ####     #### ##  #######   #####    #####            ##  ##    #####    ####     #####   ##   ##  ##  ##    ####     ####     #####   ##   ##"

      - name: Instalar dependências do sistema
        run: |
          apt update && apt install -y curl gnupg unzip wget git \
            nodejs npm libgtk-3-dev libnotify-dev libgconf-2-4 \
            libnss3 libxss1 libasound2 xvfb

      - name: Verificar versões
        run: |
          node -v
          npm -v
          npx cypress --version || echo "Cypress ainda não instalado"

      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Cache do npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar dependências do projeto
        run: npm ci

      - name: Rodar testes Cypress (headless com Xvfb)
        run: |
          Xvfb :99 & export DISPLAY=:99
          npx cypress run

      - name: Upload de vídeos (em caso de falhas)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload de screenshots (em caso de falhas)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
